# Generated by Django 3.1.7 on 2021-04-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='correct',
            new_name='current_state',
        ),
    ]
