# Generated by Django 3.1.7 on 2021-04-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210408_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='current_state',
            new_name='correct',
        ),
    ]
